/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CrossChainERC20__factory } from "./CrossChainERC20__factory";
export { ICrossChainERC20__factory } from "./ICrossChainERC20__factory";
