/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CrossChainERC20Burnable__factory } from "./CrossChainERC20Burnable__factory";
export { CrossChainERC20Pausable__factory } from "./CrossChainERC20Pausable__factory";
export { ICrossChainERC20Metadata__factory } from "./ICrossChainERC20Metadata__factory";
