/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CrossChainERC20Burnable__factory } from "./CrossChainERC20Burnable__factory";
export { CrossChainERC20Capped__factory } from "./CrossChainERC20Capped__factory";
export { CrossChainERC20FlashMint__factory } from "./CrossChainERC20FlashMint__factory";
export { CrossChainERC20Pausable__factory } from "./CrossChainERC20Pausable__factory";
