/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CrossChainERC721Burnable } from "./CrossChainERC721Burnable";
export type { CrossChainERC721Pausable } from "./CrossChainERC721Pausable";
