/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as extensions from "./extensions";
export { CrossChainERC1155__factory } from "./CrossChainERC1155__factory";
export { ICrossChainERC1155__factory } from "./ICrossChainERC1155__factory";
