/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CrossChainERC20 } from "./CrossChainERC20";
export type { ICrossChainERC20 } from "./ICrossChainERC20";
