/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from "./extensions";
export type { extensions };
export type { CrossChainERC20 } from "./CrossChainERC20";
export type { ICrossChainERC20 } from "./ICrossChainERC20";
