/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CrossChainGovernor } from "./CrossChainGovernor";
export type { ICrossChainGovernor } from "./ICrossChainGovernor";
