/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CrossChainERC1155 } from "./CrossChainERC1155";
export type { ICrossChainERC1155 } from "./ICrossChainERC1155";
