/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGenericHandler } from "./IGenericHandler";
export type { IRouterCrossTalk } from "./IRouterCrossTalk";
