/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as examples from "./examples";
export { GenericHandlerTest__factory } from "./GenericHandlerTest__factory";
