/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { RouterCrossTalk__factory } from "./RouterCrossTalk__factory";
