/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CrossChainERC721Burnable__factory } from "./CrossChainERC721Burnable__factory";
export { CrossChainERC721Pausable__factory } from "./CrossChainERC721Pausable__factory";
