/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20FlashMintSol from "./ERC20FlashMint.sol";
export type { erc20FlashMintSol };
export type { CrossChainERC20Burnable } from "./CrossChainERC20Burnable";
export type { CrossChainERC20Capped } from "./CrossChainERC20Capped";
export type { CrossChainERC20FlashMint } from "./CrossChainERC20FlashMint";
export type { CrossChainERC20Pausable } from "./CrossChainERC20Pausable";
